services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_NAME: ${MYSQL_NAME}
    volumes:
      - ./app/public:/var/www/html
    networks:
      - mysql-phpmyadmin

  db:
    image: mysql:9.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./app/sql:/var/lib/mysql
    networks:
      - mysql-phpmyadmin


  phpmyadmin:
    container_name: phpmyadmin_container
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  wordpress_data:
  db_data: